Repository okfn-brasil/querido-diario, pull requests merged in 2020-11, with the labels that each got.

#339 Add spider monitoring
  processing/data_collection/gazette/monitors.py
  processing/data_collection/gazette/settings.py
Labels: type:infrastructure

#337 Initialize database with territories information
  processing/data_collection/gazette/database/models.py
  processing/data_collection/gazette/resources/territories.csv
Labels: type:infrastructure

#276 Inserted Guidelines to maintainers
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, type:docs

#328 Misleading error message when write in the database fails.
  data_collection/gazette/pipelines.py
Labels: hacktoberfest-accepted

#374 Review of Salvador-BA spider
  data_collection/gazette/spiders/ba_salvador.py
Labels: type:spider
