Repository okfn-brasil/querido-diario, pull requests merged in 2025-01, with the labels that each got.

#1338 Habilita smartproxy para Campinas-SP
  data_collection/gazette/spiders/sp/sp_campinas.py
Labels: production, maintenance

#1329 Hotfix: Adapting Spider [df_brasilia] to Changes in the DODF Website/API
  data_collection/gazette/spiders/df/df_brasilia.py
Labels: priority, maintenance

#1297 sistema replicavel administracaopublica #1247
  data_collection/gazette/spiders/base/administracaopublica.py
  data_collection/gazette/spiders/ma/ma_nova_iorque.py
  data_collection/gazette/spiders/ma/ma_peritoro.py
  data_collection/gazette/spiders/ma/ma_turilandia.py
Labels: hacktoberfest-accepted
